---
title: "Zwyx"
author: "AJ Vaestermark, JR Walters."
date: "`r Sys.Date()`"
output: html_document
vignette: >
    %\VignetteIndexEntry{"Zwyx"}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r }

#RESULT <- NULL
#MF<-NULL
#NUMBER_OF_SCAFFOLDS <- 5397
#NUMBER_OF_WORKERS <- 30
#MANUALLY <- NUMBER_OF_SCAFFOLDS - floor(NUMBER_OF_SCAFFOLDS / NUMBER_OF_WORKERS) * NUMBER_OF_WORKERS
#pb <- txtProgressBar(max=floor(NUMBER_OF_SCAFFOLDS / NUMBER_OF_WORKERS)-1)
#for(j in 0: (floor(NUMBER_OF_SCAFFOLDS / NUMBER_OF_WORKERS)-1) ) {
#setTxtProgressBar(pb, j+1)
#scaffolds = yyx[j]
#x <- c('Danaus_poolC_Plex_BOS_HI023_M_CTTGGA_L003realigned.bam', 'MK_Plex_Mex_1742_F_GATCAG_L002realigned.bam', 'MK_Plex_NJ_116_M_GAGTGG_L008.realigned.bam', 'MK_Plex_StMFL_122_F_ATCACG_L008realigned.bam', 'MK_Plex_StMFL_109_M_ACTTGA_L007realigned.bam', 'MK_Plex_TX_T11_F_GGCTAC_L0013realigned.bam')
 #MF <- foreach(i=1:NUMBER_OF_WORKERS) %dopar% {   
#suppressMessages(    getReadCountsFromBAM(x, WL=1000, refSeqName=yyx[j*NUMBER_OF_WORKERS+i])) }
#RESULT <- c(RESULT, MF)
#}
#message()
#close(pb)

### Add additional Granges objects onto the list
#for(k in (floor(NUMBER_OF_SCAFFOLDS / NUMBER_OF_WORKERS) * (NUMBER_OF_WORKERS) + 1): NUMBER_OF_SCAFFOLDS  ) {
#scaffolds = yyx[k]
#message(scaffolds)
#MF <- suppressWarnings ( suppressMessages(    getReadCountsFromBAM(x, WL=1000, refSeqName=yyx[k])) )
#RESULT <- c(RESULT, MF)
#}

#G_RESULT <- GRangesList(RESULT)

#load(file="G.RESULT")

library(Zwyx)
library(doParallel)
#library(GenomicRanges)
library("foreach", "iterators", "parallel")
library(Rsamtools)
data(G.RESULT)
plotMedianReadCounts(G_RESULT)
ratiosCorrelation(G_RESULT)
#findChimericScaffold(G_RESULT)



```

